server:
  error:
    path: /error
#    whitelabel:
#      enabled: false #???????????
  ssl: #证书https
    key-store: sang.p12
    key-alias: tomcathttps
    key-store-password: changeit
  servlet:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
    max-connections: 500

#  邮件配置
#spring:
#  mail:
#    host: smtp.qq.com
#    port: 465
#    username: 422892383@qq.com
#    password: fcyqztkctnoscabi
#    default-encoding: UTF-8
#    properties:
#      mail:
#        debug: true
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory

#生产/开发环境配置
spring:
  profiles:
    active: dev
#  mvc:
#    pathmatch:
#      use-suffix-pattern: true #??????? server.servlet.path?????????
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  http:
    encoding:
      force-response: true  #fastjson相应编码
  servlet:
    multipart: #图片上传的细节配置
      enabled: true
      file-size-threshold: 0
      location: D:\\czw
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://localhost:3306/springboot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/jpa?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456
#  配置多数据源
#    one:
#      type: com.alibaba.druid.pool.DruidDataSource
#      username: root
#      password: 123456
#      url: jdbc:mysql://localhost:3306/jpa?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
#    two:
#      type: com.alibaba.druid.pool.DruidDataSource
#      username: root
#      password: 123456
#      url: jdbc:mysql://localhost:3306/sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: 123456 #一般没密码需要注释，否则会报错ERR Client sent AUTH, but no password is set
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
#  security:
#    user:
#      name: czw
#      password: 123456
#      roles: admin

#定义常量数据
czw:
  name: 陈章文
  number: 180878
  boy: true

maria:
  name: 鸭鸭同学
  money: 10000
  girl: true

#  shiro配置
shiro:
  enabled: true
  web:
    enabled: true
  loginUrl: /login #默认为“/login.jsp”
  successUrl: /index #默认成功地址为“/”
  unauthorizedUrl: /unauthorized
  sessionManager: #是否允许通过Cookie实现会话跟踪
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true